services:
  - type: web
    name: school-bulletin-board
    env: ruby
    plan: free
    region: singapore
    branch: main
    buildCommand: bundle install && bundle exec rails assets:precompile
    startCommand: bundle exec rails server -p $PORT -b 0.0.0.0
    healthCheckPath: /up
    preDeployCommand: bundle exec rails db:migrate
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "1"
      - key: RAILS_SERVE_STATIC_FILES
        value: "1"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: school-bulletin-board-db
          property: connectionString

databases:
  - name: school-bulletin-board-db
    plan: free
    region: singapore
    version: 17